---
- name: Install CMake
  apt: name={{item}} state=installed
  with_items:
    - cmake
    - cmake-gui
    - cmake-curses-gui
  become: true
- name: Install additional tools
  apt: name={{item}} state=installed
  with_items:
    - ninja-build
    - exuberant-ctags
    - valgrind
    - clang-format
  become: true
