---
- name: Install Git
  apt: name={{item}} state=installed
  with_items:
    - git
    - git-gui
    - gitk
  become: true
- name: Make sure that category exists in Git config
  lineinfile:
    create: yes
    destfile: "{{homedir}}/.gitconfig"
    line: '[user]'
- name: Set name for Git
  lineinfile:
    destfile: "{{homedir}}/.gitconfig"
    regexp: 'name = '
    insertafter: '^[user]'
    line: "\tname = {{username}}"
- name: Set mail for Git
  lineinfile:
    destfile: "{{homedir}}/.gitconfig"
    regexp: 'email = '
    insertafter: '^[user]'
    line: "\temail = {{usermail}}"
- name: Install CMake
  apt: name={{item}} state=installed
  with_items:
    - cmake
    - cmake-gui
    - cmake-curses-gui
  become: true
- name: Install additional tools
  apt: name={{item}} state=installed
  with_items:
    - ninja-build
    - exuberant-ctags
  become: true
