---
- name: Install CMake
  apt: name={{item}} state=installed
  with_items:
    - cmake
    - cmake-gui
    - cmake-curses-gui
  become: true
- name: Install additional tools
  apt: name={{item}} state=installed
  with_items:
    - ninja-build
    - exuberant-ctags
    - valgrind
    - clang-format
  become: true
- name: Deactivate network notifications by default
  copy:
    src: networkmanagement.notifyrc
    dest: "{{homedir}}/.config/networkmanagement.notifyrc"
    force: no
  when: desktop_environment is defined and desktop_environment == "KDE"
